# Generated by Django 4.2.4 on 2023-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='imageURL',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
