# Generated by Django 4.2.4 on 2023-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('githubLink', models.URLField(blank=True)),
                ('youtubeLink', models.URLField(blank=True)),
                ('playTestLink', models.URLField(blank=True)),
            ],
        ),
    ]
