# Generated by Django 4.2.4 on 2023-08-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_language_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('c', 'C/C++'), ('py', 'PYTHON'), ('unity', 'UNITY'), ('java', 'JAVA'), ('opengl', 'OpenGL')], default='c', max_length=100),
        ),
    ]
