# Generated by Django 4.2.4 on 2023-08-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('c', 'C/C++'), ('py', 'PYTHON'), ('unity', 'UNITY'), ('java', 'JAVA')], default='c', help_text='Programming Language', max_length=100),
        ),
    ]
