# Generated by Django 4.2.4 on 2023-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='githubLink',
            new_name='githubURL',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='playTestLink',
            new_name='youtubeURL',
        ),
        migrations.RemoveField(
            model_name='project',
            name='youtubeLink',
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('C', 'C/C++'), ('PYTHON', 'PYTHON'), ('UNITY', 'UNITY'), ('JAVA', 'JAVA')], default='C', help_text='Programming Language used in the project', max_length=100),
        ),
    ]
