# Generated by Django 4.2.4 on 2023-08-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_githublink_project_githuburl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='playTestURL',
            field=models.URLField(blank=True),
        ),
    ]
