# Generated by Django 4.2.4 on 2023-08-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, choices=[('Django', 'DJANGO'), ('OpenGL', 'OPENGL'), ('Selenium', 'SELENIUM'), ('P5', 'P5JS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('C', 'C/C++'), ('UNITY', 'UNITY'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('JAVASCRIPT', 'JAVASCRIPT')], max_length=10),
        ),
    ]
