# Generated by Django 4.2.4 on 2023-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_framework_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, choices=[('Django', 'DJANGO'), ('OpenGL', 'OPENGL'), ('Selenium', 'SELENIUM'), ('P5', 'P5JS'), ('WinBGIM', 'WINBGIM')], max_length=10),
        ),
    ]
